name: pii
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.9.1
    - pytorch-cpu=1.7.1
    - spacy=3.2.0
    - pip=21.0
    - Cython=0.29.24
    - pytest=6.2.5
    - transformers=4.12.3
    - faker==9.8.1
    - sentencepiece=0.1.95
    - nltk=3.6.5
    - protobuf=3.17.2
    - pip:
      - datasets==1.15.1
      - langid==1.1.6